#!/bin/bash

outputs=$(pactl list short sinks | grep -v "alsa_output.platform-snd_aloop.0.analog-stereo" | awk '{print$1}')
command=$1

if [ $command == "increase" ]
then
	for current_sink in $outputs
	do
		pactl set-sink-volume $current_sink +3%
		volume=$(pactl get-sink-volume $current_sink | awk '{print$5}' | head -1 | sed 's/%//g')
		[ $volume -gt 97 ] && pactl set-sink-volume $current_sink 100%
	done
elif [ $command == "decrease" ]
then
	for current_sink in $outputs
	do
		pactl set-sink-volume $current_sink -4%
	done
elif [ $command == "mute" ]
then
	for current_sink in $outputs
	do
		mute_state=$(pactl get-sink-mute $current_sink | awk '{print$2}')
		[ $mute_state == yes ] && pactl set-sink-mute $current_sink 0 || pactl set-sink-mute $current_sink 1
	done
fi
