#!/bin/bash

update() {
	orange='\033[0;33m'
	NC='\033[0m'
        target=$1
        msg=$(cd $target; git pull)
        if [ "$msg" == "Already up to date." ]
        then
                echo -e "${orange}$dir:${NC} $msg"
		echo $target >> $updated &
        else
		echo "seems there are updates to $target"
		echo $target >> $outdated &
        fi
        return
}


outdated=$HOME/.outdated
updated=$HOME/.updated
[ -p $updated ] || mkfifo $updated
[ -p $outdated ] || mkfifo $outdated



current=$(pwd)

cd $HOME/AUR/

pids=()
for dir in $(ls)
do
        update $dir &
	pids+=($!)
done

echo ""
echo "let's wait..."

wait ${pids[@]}

echo "capturando conteudo de updated..."
up=$(cat $updated)



echo $up
for c in $up
do
	echo $c
done





echo "removendo arquivos..."
rm $outdated
rm $updated
echo "pronto."


cd $current



















